### ISSUE TITLE
PWM Fan Mod feature request

### ISSUE THREAD

**Issue by shupershuff** [blazoncek/WLED#10]
**Describe the solution you'd like**
If possible it would be ideal if the PWM fan mod can be managed via the usermod menu (similar to how you can with the multi relay mod).
Ideally there would be an option to set the Pin and also the ability to set static fixed % values for PWM for each fan.

It would also be ideal if the % values for each PWM fan could be exposed to MQTT so that these can be remotely changed by things such as Home Assistant.

**Comment by blazoncek** [comment]
It is possible to modify all parameters using Usermod settings page.
Usermod is intended at single PWM output though.

I will consider adding MQTT and JSON API support.

**Comment by blazoncek** [comment]
JSON API implemented in c6578870f0c908a93510e18624a09682565ae93a.

**Comment by dosipod** [comment]
Now you going to cost us more money cause we have to buy a lot of fans , thank you 
![image](https://user-images.githubusercontent.com/87589371/179021214-fbde13f9-2cd5-4ee6-bebf-f15148cfc9c7.png)

**Comment by blazoncek** [comment]
Happened to me as well.
We need to thank @srg74 for original request.

**Comment by dosipod** [comment]
curl http://ip/json -d {"PWM-fan":{"speed":30,"lock":true}} -H "Content-Type: application/json"    works and i can control it .

**Comment by blazoncek** [comment]
Added manual speed control in UI. It will override temperature setting if >0.
Can be also set using JSON API.

**Comment by blazoncek** [comment]
@shupershuff if you want to alpha test MQTT try https://github.com/Aircoookie/WLED/tree/PWM-fan-HA

**Comment by shupershuff** [comment]
Hi there, cool to see this has progressed heaps. 
Currently I'm using segments in WLED with 2 of these segments being for some fans. These segments are using the White LED option, I connect the pin to the MOSFET controlling the fans. It's a bit rough but it's been working and I can control in Home Assistant (HA just sees the fans as dimmable lights).

It sounds like with this mod I could control a fan using either the UI, MQTT, or JSON API which is great.
I presume that tacho pin can be set to -1 if there isn't one or if I've ran out of PINs :)
Is there capability to add more than one fan?

For context, my use case fits well outside of why this mod was built, my WLED controller controls fans on a dead motherboard and dead GPU that I've framed on the wall.
![image](https://user-images.githubusercontent.com/63577525/200717862-7a80409b-28b0-4d00-a24e-588b3d4a9698.png)

**Comment by blazoncek** [comment]
The primary reason for this usermod is temperature control of WLED enclosure and so a primary input is temperature usermod.
It will not be possible to control more than 1 fan with this usermod.

Your solution is appropriate IMO and better suited than this usermod.

I would still like you to test if it fulfils your initial request and/or close this issue.

**Comment by blazoncek** [comment]
As there is no interest of finishing up on this I am closing the issue.
