### ISSUE TITLE
2D - Labels of slider for Effect 2D Blackhole wrong

### ISSUE THREAD

**Issue by lost-hope** [blazoncek/WLED#19]
### What happened?

When changing the Inner Freq sliders, the outer ring changes behaviour and vise versa

### To Reproduce Bug

Use 2D Blackhole  and use Sliders

### Expected Behavior

Inner Sliders control Inner circle and outer slider control outer circle

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-bl0 (build 2205011)

### Which microcontroller/board are you seeing the problem on?

ESP8266, ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Fixed in 4963a5797be218ffaa71ced864d6a16a14c71617
