### ISSUE TITLE
2D - Setting bars are missalined

### ISSUE THREAD

**Issue by lost-hope** [blazoncek/WLED#21]
### What happened?

there is a margin on the right, but not on the left in the web ui settings window

### To Reproduce Bug

Open the Settings window

### Expected Behavior

either no margin or margin on both sides

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.0-bl0 (build 2205011)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Fixed in 4e8030bd815df179e19ad9bbc08a9b224ac5661d
