### ISSUE TITLE
2D - Update of legacy Effects

### ISSUE THREAD

**Issue by lost-hope** [blazoncek/WLED#22]
Here some ideas, some might be too complex, some are easier:
 # Ideas / TODO: 
- [ ] Tetrix
> Having actual tetris like block falling down. 

- [x] Fireworks
> Have rockets fly up (small arced trail) and explode in a circle
> or without fly trail

- [ ] Heartbeat
>EKG line with slight variation  in width

- [ ] Lightning
> having lighning come down vom the top of the matrx

- [x] Sparkle / Sparkle Dark / Sparkle +
> single led Sparkle instead of line

- [x] Rain
> having a small ring going out from the drop impact point

New Effects:

- [ ] DVD bouncing
> having a small tile bounce around in the matrix like the old DVD screensaver

- [x] Fixed text in scrolling text effect when the string fits on the matrix

- [x]  Scrolling text

- [x] Drip

- [x] Glitter/Solid Glitter

- [x] PopCorn

- [] PopCorn
# Backlog:
- [ ] Tetrix
> Having actual tetris like block falling down. 
> ```I will not be implementing proper Tetris since it would require too much memory using current approach. If it is rewritten from scratch it may be implemented in full using leds[] array.```

Comment when you have made some of them, so i can tick them off. and i can add other ideas to the list that are mentioned via comments

**Comment by dosipod** [comment]
Scrolling text effect i

**Comment by blazoncek** [comment]
You are pushing it now. 😁

**Comment by blazoncek** [comment]
I will not be implementing proper Tetris since it would require too much memory using current approach.

If it is rewritten from scratch it may be implemented in full using leds[] array.

**Comment by blazoncek** [comment]
Please add to the list:
- Drip
- Glitter/Solid Glitter
- PopCorn

**Comment by blazoncek** [comment]
Rain effect is based on Fireworks (not Starburst or 1D variant) which has been made 2D aware.
Unfortunately Rain uses a hack to make raindrops from firework bursts which is incompatible with 2D in it's current implementation.
The best replacement ATM is 2D Matrix effect.

Similarly Heartbeat can be (very roughly) approximated using 2D Pulser effect.

**Comment by blazoncek** [comment]
Rain also done.
DVD bouncing is a new effect that may be done by someone else (a similar effect is in place as Floating Blobs)

**Comment by blazoncek** [comment]
Even though not all effects above were made 2D aware I am closing this issue since @ewoudwijma implemented pixel mapping available in 1e4f8be74b7fbc7c0e68b96d7b215527d519647c
This introduces a new *dimension* to legacy effects in a simple way.
