### ISSUE TITLE
Display JPEGs on a Matrix 

### ISSUE THREAD

**Issue by dosipod** [blazoncek/WLED#23]
I have found an existing project for  esp8266 web server  that can display JPEGs on a matrix . i hope that will be  a good addition to 
the 2d functions .

https://github.com/datasith/Ai_Demos_ESP8266/tree/master/webserver_jpeg_ws2812

**Comment by embedded-creations** [comment]
This guy has great image decoding libraries, I'd use his over any random libraries:

https://github.com/bitbank2/JPEGDEC

I already added a Usermod/effect for Animated GIF decoding to my branch using his decoder

**Comment by dosipod** [comment]
That is fine , I am really glade you already tested a better decoder and would support JPEGs on a Matrix . I hope blazoncek is also considering the same 

I am trying to look for the usermod you mentioned in your branch but cant see it under https://github.com/embedded-creations/WLED/tree/master/usermods

**Comment by embedded-creations** [comment]
It's here: https://github.com/embedded-creations/WLED/tree/FastLED_2D/usermods/AnimatedGIFs

**Comment by blazoncek** [comment]
I will be adding SD card support 1st and then I'll tackle displaying JPEGs and GIFs.

**Comment by dosipod** [comment]
That would be nice even though the example listed above uses a web server to upload the JPEGs  . This way there is no need for the extra HW . If we are to  limit the same to availability of SD then might be we are limiting the usage base  , as  both of you are expert in this , I would trust the way you do it the most practical . And I have SD/display models so I am covered

**Comment by blazoncek** [comment]
Not planned.
SD card support is scheduled upstream.
