### ISSUE TITLE
Extend ALT 4LD and Rotary Usermod with custom sliders and preset

### ISSUE THREAD

**Issue by ewoudwijma** [blazoncek/WLED#25]
As discussed on discord

Add support for custom sliders
- use (custom) slider names
- do not show unused sliders
-  rotary can modify them

Presets (bonus)
- Show current preset
- modify preset using rotary

**Comment by blazoncek** [comment]
Bonus requets still pending, others done.

**Comment by blazoncek** [comment]
This 793c878c6674cdb7ed95fb3ec21634af26010fb3 should crudely fulfill this issue.

**Comment by ewoudwijma** [comment]
👍
