### ISSUE TITLE
Preset loading issue with 2D

### ISSUE THREAD

**Issue by Shaps-77** [blazoncek/WLED#28]
### What happened?

When using a macro button to scroll presets, they scroll correctly in UI but the LED output is unchanged.
If a preset button is 'directly' pressed in UI, the preset loads correctly and LED output is as expected.

### To Reproduce Bug

Setup multiple presets with differing lighting effects (eg. 1-5 in my case)
Create a macro to scroll presets    win&P1=1&P5=30&PL=~

### Expected Behavior

LED output should change in line with UI

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.0-bl0 (build 2205251)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

Thank you :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
This only happens with HTTP API preset that changes current presets.
Known issue.

**Comment by blazoncek** [comment]
I think I have found the bug.

**Comment by Shaps-77** [comment]
Quick test of functionality in conjunction with usermods
* ROTARY_ENCODER_BRIGHTNESS_COLOR
* PIRSWITCH 
and everything is working as expected.

I can't thank you enough Blaž 🙏🙌🍻
