### ISSUE TITLE
make pixels outside grouping and spacing black

### ISSUE THREAD

**Issue by ewoudwijma** [blazoncek/WLED#30]
Otherwise when changing effects / presets / grouping and spacing values, those 'gap' pixels will keep the last color shown

**Comment by blazoncek** [comment]
Added clearing of whole segment if spacing has changed by JSON API (json.cpp, l:75).
I am not sure that this (clearing spacing) is always a desirable. I would love @Aircoookie comment on this.

**Comment by blazoncek** [comment]
Additional fix available in 6c6849d8d7715e5f7adc7575a973c7ea04dd2259
I am closing as clearing only happens on segment change which is ok IMO.
