### ISSUE TITLE
Show in some way the slider name on mobile UI

### ISSUE THREAD

**Issue by ewoudwijma** [blazoncek/WLED#34]
It's pretty unusable on mobile if you don't know what the slider does when moving the slider

I would say some kind of tooltip similar to how the slider value is shown when changing the slider

**Comment by blazoncek** [comment]
Agreed but it gets crowded on phone screen.
Experiment by removing `hd` class in index.htm from slider name elements (sliderLabelXXX).

**Comment by blazoncek** [comment]
Commit https://github.com/blazoncek/WLED/commit/94a79b57e94d8fea131ca7fcbb4bc6b51bd8e626 should close this issue.
