### ISSUE TITLE
After adding new preset, not possible to select other presets and new preset

### ISSUE THREAD

**Issue by ewoudwijma** [blazoncek/WLED#35]
After adding new or updating existing preset, not possible to select other presets and new preset, refresh needed to solve

**Comment by blazoncek** [comment]
I am not sure I understand.
When you save a preset, it is actually saved as a state (or if you provided API) on the ESP. UI unfortunately does not know *all* parameters needed for the state so cannot *know* new preset content until you reload the whole UI.

As for the other part: After I save a preset I am able to select any other preset.

**Comment by ewoudwijma** [comment]
You are right indeed, after creating or updating a preset, I can still select the other presets. Only when I select the created or saved preset, nothing happens. Reload needed to this preset selectable. Tested this in SR and there no reload is needed

**Comment by blazoncek** [comment]
This 8f72e0ab833cf32a5a4c4f2b3647e272eea6f974 should fix it.
