### ISSUE TITLE
Hardware Setup with >4 Led Outputs does not work

### ISSUE THREAD

**Issue by versamodule** [blazoncek/WLED#45]
### What happened?

I am using release 0.14.0-b5, on a ESP32-S3 Devkit. Everything works just fine with one exception.
I have 5 Ws281x led strips. Each strip has 75 leds on it.
Strips 1-4 work just fine, but the 5’th does not even light up.
Yet, if I go into Config → LED Preferences and under Hardware setup I swap the GPIO pins of the 4 & 5’th strings, then the 5’th string works and the 4’th does not.

LED outputs are configured as such.
Segment 0 = Start LED 0, Stop LED 375

Then Under Config → LED Preferences
#1) Start 0, Length 75, GPIO 14
#2) Start 75, Length 75, GPIO 13
#3) Start 150, Length 75, GPIO 12
#4) Start 225, Length 75, GPIO 11
#5) Start 300, Length 75, GPIO 10

Any ideas what might be going on here?

### To Reproduce Bug

Attach more than 4 LED strips

### Expected Behavior

Expected 5 strips to work

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0-b5

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
S3 only supports 4 RMT outputs.
It can support additional 3 virtual buses.

**Comment by blazoncek** [comment]
BTW this repo is currently unmaintained.
